name: Tamil Song Downloader and Trimmer

on:
  schedule:
    - cron: '30 11 * * *'  # Runs daily at 4:55 PM IST (11:30 AM UTC)
  workflow_dispatch:

jobs:
  download-trim-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yt-dlp and ffmpeg
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Save cookies
        run: echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Download Tamil Trending Songs
        run: |
          mkdir -p songs
          yt-dlp --cookies cookies.txt -x --audio-format mp3 --embed-metadata \
            --output "songs/%(playlist_index)s - %(title)s.%(ext)s" \
            "https://www.youtube.com/playlist?list=PLrEnWoR732-BHrPp_Pm8_VleD68f9s14-"

      - name: Trim Songs to Fit 1.5GB
        run: |
          MAX_SIZE=1572864000
          CUR_SIZE=$(du -cb songs/*.mp3 | tail -1 | awk '{print $1}')
          echo "Total size: $CUR_SIZE / $MAX_SIZE"

          if [ "$CUR_SIZE" -le "$MAX_SIZE" ]; then
            echo "No need to trim."
            exit 0
          fi

          echo "Trimming files..."
          for file in $(ls -1v songs/*.mp3); do
            CUR_SIZE=$(du -cb songs/*.mp3 | tail -1 | awk '{print $1}')
            [ "$CUR_SIZE" -le "$MAX_SIZE" ] && break
            ffmpeg -y -i "$file" -ss 0 -t 60 -af "afade=t=out:st=50:d=10" "trimmed.mp3"
            mv trimmed.mp3 "$file"
          done

      - name: Save list of songs
        run: |
          ls -1v songs/*.mp3 > songs/list.txt

      - name: Commit trimmed songs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add songs/
          git commit -m "🎵 Auto update Tamil songs" || echo "No changes to commit"
          git push
